### ISSUE TITLE
Possibility of MIT/BSD license for the dilogarithm code?

### ISSUE THREAD

**Issue by cesss** [Expander/polylogarithm#9]
Hi!

I'd like to know if there's any possibility of using your dilogarithm code under a MIT/BSD license, or at least if you could add a statically link exception to the license. I know that LGPL code can be used from MIT/BSD projects, but however this requires dynamic linking of the LGPL code, and in some platforms/systems/situations dynamic linking is a burden.

**Comment by Expander** [comment]
Hi cesss,

that's a good idea! I could re-release the code under the MIT license.

I guess I should create a new version (probably 6.0.0) with the changed license. Would that be OK? Or would you recommend another approach?

Best regards,
Alex

**Comment by cesss** [comment]
That would be great, thanks a lot!! By the way, if you want your library to be cited in some special way, just tell me (I tell this because some code authors provide LaTeX (BibTeX) syntax for citing their work)

**Comment by Expander** [comment]
Hi cesss,

I'm currently preparing the new release 6.0.0, which will be licensed under the MIT license. I will notify you when I'm done (probably within the next few days.)

If you have the chance to cite this package, I'd be very happy! :) 
You may use something like this for the next version 6.0.0:
~~~
@software{polylogarithm,
    author       = {{Alexander Voigt}},
    title        = {{Polylogarithm}},
    year         = "2020",
    version      = {6.0.0},
    url          = {https://github.com/Expander/polylogarithm},
    note         = "[License: MIT]"
}
~~~

Just out of curiosity, will you use the routines in a high-energy physics project?

**Comment by cesss** [comment]
> Just out of curiosity, will you use the routines in a high-energy physics project?

Thermal radiation heat transfer. More specifically, for the closed-form view factor between two arbitrary polygons as described in the [1993 Schröder/Hanrahan paper](https://graphics.stanford.edu/papers/formfactor/). Actually, they provide a dilogarithm implementation in their sample code, but it's old code from the 90s and I don't know how well tested it is, and also the license terms are not clear.

I'm implementing several methods for calculating view factors: I already have implemented GPU-based hemicubes, as well as exact solutions for rectangles in canonical cases (from the [catalog by John R Howell](http://www.thermalradiation.net/tablecon.html)). Next is raytraced-based view factors (with BVH acceleration), and also the closed-form by Schröder/Hanrahan, for which I need a working dilogarithm implementation.

The project is actually a coupled model (CFD+thermal radiation), but the dilogarithm is for the radiation part. The code will be published (quite likely here in GitHub), I can keep you informed if you wish 😃

**Comment by Expander** [comment]
Hi cesss,

that sounds very interesting and seems to bring a lot of fun (although I'm afraid I have no idea about any of the details). :)
Anyway, it is fascinating that the dilogarithm appears in so many fields -- I guess it must have something to do with nature itself...

I have just released version 6.0.0 under the MIT license. I hope this helps! :)

Best regards and happy researching,
Alex

**Comment by Expander** [comment]
P.S.: Yes, please keep me informed, your project sounds very interesting!

**Comment by cesss** [comment]
Thanks, thanks, thanks a lot!! 😃  Yes, I'll keep you informed!! (and yes, this project is lots of fun for me, because I have always loved radiosity and radiation heat transfer)
